apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: auth
type: Opaque
data:
  DATABASE_URL: ALTERADO-POR-SEGURANÇA==
  MASTER_KEY: ALTERADO-POR-SEGURANÇA=
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-secret
  namespace: flag
type: Opaque
data:
  DATABASE_URL: ALTERADO-POR-SEGURANÇA
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-secret
  namespace: targeting
type: Opaque
data:
  DATABASE_URL: ALTERADO-POR-SEGURANÇA=
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: evaluation
type: Opaque
data:
  SERVICE_API_KEY: ALTERADO-POR-SEGURANÇA=
  REDIS_URL: ALTERADO-POR-SEGURANÇA=
  AWS_SQS_URL: ALTERADO-POR-SEGURANÇA=
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: analytics
type: Opaque
data:
  AWS_SQS_URL: ALTERADO-POR-SEGURANÇA=

